# Generated by Django 2.1.3 on 2019-03-26 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dengon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameTo', models.CharField(default='', max_length=50)),
                ('mailTo', models.EmailField(default='', max_length=100)),
                ('nameFrom', models.CharField(default='', max_length=50)),
                ('nameTakenBy', models.CharField(default='', max_length=50)),
                ('mailTakenBy', models.EmailField(default='', max_length=100)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('requirement', models.IntegerField(default=0)),
                ('phoneNumber', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='')),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
