# Generated by Django 2.0.9 on 2019-03-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dengon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_list',
            new_name='dengon',
        ),
    ]
