# Generated by Django 2.0.9 on 2019-03-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengon', '0002_auto_20190304_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dengon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dengon',
            name='name',
        ),
        migrations.AlterField(
            model_name='dengon',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
