# Generated by Django 2.0.9 on 2019-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengon', '0003_auto_20190304_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dengon',
            name='nameFrom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dengon',
            name='nameTo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
