# Generated by Django 2.0.9 on 2019-03-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengon', '0004_auto_20190304_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
